layout_spectrum: 0.1787234
typography_spectrum: 0.3843457
color:
  saturation: 0.5268667
  brandStrength: 0.5255319
  lightness: 0.3190074
  rhythmicContrast: 0.3275147
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Valerio Spinaci P.A.
